INSERT INTO publications (
  title,
  release_date,
  pdf_file,
  file_url,
  cover_url,
  summary,
  description,
  publication_category,
  catalog_number,
  publication_number,
  isbn,
  created_at,
  updated_at
)
VALUES
(
  'Kabupaten Bondowoso Dalam Angka 2024',
  '2024-02-20',
  NULL,
  'publications/publikasi1.pdf',
  'covers/cantikku.png',
  'Publikasi tahunan yang menyajikan indikator statistik utama Kabupaten Bondowoso.',
  'Publikasi ini memuat data lintas sektor seperti kependudukan, ekonomi, sosial, dan lingkungan hidup.',
  1,
  1102001,
  'BDA-2024',
  '978-602-1234-56-7',
  NOW(), NOW()
),
(
  'Statistik Kesejahteraan Rakyat Kabupaten Bondowoso 2023',
  '2023-12-10',
  NULL,
  'publications/publikasi1.pdf',
  'covers/cantikku.png',
  'Publikasi statistik yang membahas kondisi kesejahteraan masyarakat.',
  'Menyajikan data pendidikan, kesehatan, dan perumahan masyarakat Bondowoso.',
  2,
  1102002,
  'KESRA-2023',
  '978-602-1234-78-9',
  NOW(), NOW()
),
(
  'Produk Domestik Regional Bruto Kabupaten Bondowoso Menurut Lapangan Usaha 2019–2023',
  '2024-01-05',
  NULL,
  'publications/publikasi1.pdf',
  'covers/cantikku.png',
  'Publikasi PDRB Kabupaten Bondowoso berdasarkan lapangan usaha.',
  'Menyajikan data PDRB seri 2019–2023 sebagai dasar analisis ekonomi daerah.',
  1,
  1102003,
  'PDRB-2023',
  '978-602-2234-11-2',
  NOW(), NOW()
),
(
  'Statistik Pendidikan Kabupaten Bondowoso 2023',
  '2023-10-20',
  NULL,
  'publications/publikasi1.pdf',
  'covers/cantikku.png',
  'Publikasi statistik sektor pendidikan di Kabupaten Bondowoso.',
  'Menyajikan data partisipasi sekolah, tingkat pendidikan, dan fasilitas pendidikan.',
  1,
  1102004,
  'PEND-2023',
  '978-602-2234-33-4',
  NOW(), NOW()
),
(
  'Statistik Kesehatan Kabupaten Bondowoso 2023',
  '2023-09-18',
  NULL,
  'publications/publikasi1.pdf',
  'covers/cantikku.png',
  'Publikasi statistik yang membahas kondisi kesehatan masyarakat.',
  'Berisi data fasilitas kesehatan, tenaga medis, dan indikator kesehatan utama.',
  1,
  1102005,
  'KES-2023',
  '978-602-2234-44-5',
  NOW(), NOW()
);
